### ISSUE TITLE
faasensor timeout

### ISSUE THREAD

**Issue by Haringstad** [ntilley905/faastatus#12]
**Describe the bug**
The component, and therefore the sensor will never load

**To Reproduce**
1. restart HA

**Expected behavior**
The component should be loaded and the sensor should be available

**Configuration**
```
- platform: faastatus
  airport: JFK
```

**Logs**
```
2020-06-07 22:54:23 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for faastatus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-06-07 22:54:41 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform faastatus is taking over 10 seconds.
2020-06-07 22:54:42 ERROR (MainThread) [custom_components.faastatus.sensor] [TimeoutError] 

```

**Home Assistant Information:**
 - Environment: Home Assistant Core
 - Version 0.110.5
**Additional context**
Because I do fly a lot, it would be nice to get this working. I don't understand where the timeout comes from. Like to be advised how to perform some debugging by hand.

**Comment by ntilley905** [comment]
The FAA API unfortunately _does_ go down a lot. That makes it tough to debug these issues because it's tough to know if it's a problem with the sensor, the local instance, or the API server. 

The best way to debug this is to see if you can hit the API yourself. If you have access to the command line, the best way to do that is just by running `curl https://soa.smext.faa.gov/asws/api/airport/status/JFK` or whatever airport you want to test.

I'll need to look into how I have it coded to see if I can handle timeouts better (I almost certainly can). I'll give it a look tomorrow, but if you see the timeout error and can let me know if you can get a response from the command line, that would definitely be helpful.

**Comment by Haringstad** [comment]
@ntilley905 I've been testing from the command line and that works fine:

```
 while :; do date ; curl https://soa.smext.faa.gov/asws/api/airport/status/JFK; echo ""; sleep 15; done
Mon Jun  8 08:47:18 CEST 2020
{"Name":"John F Kennedy Intl","City":"New York","State":"NY","ICAO":"KJFK","IATA":"JFK","SupportedAirport":true,"Delay":false,"DelayCount":0,"Status":[{"Reason":"No known delays for this airport"}],"Weather":{"Weather":[{"Temp":["A Few
 Clouds"]}],"Visibility":[10.00],"Meta":[{"Credit":"NOAA's National Weather Service","Url":"http://weather.gov/","Updated":"Last Updated on Jun 8 2020, 1:51 am EDT"}],"Temp":["64.0 F (17.8 C)"],"Wind":["North at 6.9"]}}
Mon Jun  8 08:47:34 CEST 2020
{"Name":"John F Kennedy Intl","City":"New York","State":"NY","ICAO":"KJFK","IATA":"JFK","SupportedAirport":true,"Delay":false,"DelayCount":0,"Status":[{"Reason":"No known delays for this airport"}],"Weather":{"Weather":[{"Temp":["A Few
 Clouds"]}],"Visibility":[10.00],"Meta":[{"Credit":"NOAA's National Weather Service","Url":"http://weather.gov/","Updated":"Last Updated on Jun 8 2020, 1:51 am EDT"}],"Temp":["64.0 F (17.8 C)"],"Wind":["North at 6.9"]}}
Mon Jun  8 08:47:50 CEST 2020
{"Name":"John F Kennedy Intl","City":"New York","State":"NY","ICAO":"KJFK","IATA":"JFK","SupportedAirport":true,"Delay":false,"DelayCount":0,"Status":[{"Reason":"No known delays for this airport"}],"Weather":{"Weather":[{"Temp":["A Few
 Clouds"]}],"Visibility":[10.00],"Meta":[{"Credit":"NOAA's National Weather Service","Url":"http://weather.gov/","Updated":"Last Updated on Jun 8 2020, 1:51 am EDT"}],"Temp":["64.0 F (17.8 C)"],"Wind":["North at 6.9"]}}
Mon Jun  8 08:48:05 CEST 2020
{"Name":"John F Kennedy Intl","City":"New York","State":"NY","ICAO":"KJFK","IATA":"JFK","SupportedAirport":true,"Delay":false,"DelayCount":0,"Status":[{"Reason":"No known delays for this airport"}],"Weather":{"Weather":[{"Temp":["A Few
 Clouds"]}],"Visibility":[10.00],"Meta":[{"Credit":"NOAA's National Weather Service","Url":"http://weather.gov/","Updated":"Last Updated on Jun 8 2020, 1:51 am EDT"}],"Temp":["64.0 F (17.8 C)"],"Wind":["North at 6.9"]}}
Mon Jun  8 08:48:22 CEST 2020
{"Name":"John F Kennedy Intl","City":"New York","State":"NY","ICAO":"KJFK","IATA":"JFK","SupportedAirport":true,"Delay":false,"DelayCount":0,"Status":[{"Reason":"No known delays for this airport"}],"Weather":{"Weather":[{"Temp":["A Few
 Clouds"]}],"Visibility":[10.00],"Meta":[{"Credit":"NOAA's National Weather Service","Url":"http://weather.gov/","Updated":"Last Updated on Jun 8 2020, 1:51 am EDT"}],"Temp":["64.0 F (17.8 C)"],"Wind":["North at 6.9"]}}
Mon Jun  8 08:48:37 CEST 2020
{"Name":"John F Kennedy Intl","City":"New York","State":"NY","ICAO":"KJFK","IATA":"JFK","SupportedAirport":true,"Delay":false,"DelayCount":0,"Status":[{"Reason":"No known delays for this airport"}],"Weather":{"Weather":[{"Temp":["A Few
 Clouds"]}],"Visibility":[10.00],"Meta":[{"Credit":"NOAA's National Weather Service","Url":"http://weather.gov/","Updated":"Last Updated on Jun 8 2020, 1:51 am EDT"}],"Temp":["64.0 F (17.8 C)"],"Wind":["North at 6.9"]}}
Mon Jun  8 08:48:53 CEST 2020
{"Name":"John F Kennedy Intl","City":"New York","State":"NY","ICAO":"KJFK","IATA":"JFK","SupportedAirport":true,"Delay":false,"DelayCount":0,"Status":[{"Reason":"No known delays for this airport"}],"Weather":{"Weather":[{"Temp":["A Few
 Clouds"]}],"Visibility":[10.00],"Meta":[{"Credit":"NOAA's National Weather Service","Url":"http://weather.gov/","Updated":"Last Updated on Jun 8 2020, 1:51 am EDT"}],"Temp":["64.0 F (17.8 C)"],"Wind":["North at 6.9"]}}
Mon Jun  8 08:49:09 CEST 2020
{"Name":"John F Kennedy Intl","City":"New York","State":"NY","ICAO":"KJFK","IATA":"JFK","SupportedAirport":true,"Delay":false,"DelayCount":0,"Status":[{"Reason":"No known delays for this airport"}],"Weather":{"Weather":[{"Temp":["A Few
 Clouds"]}],"Visibility":[10.00],"Meta":[{"Credit":"NOAA's National Weather Service","Url":"http://weather.gov/","Updated":"Last Updated on Jun 8 2020, 1:51 am EDT"}],"Temp":["64.0 F (17.8 C)"],"Wind":["North at 6.9"]}}
Mon Jun  8 08:49:25 CEST 2020
{"Name":"John F Kennedy Intl","City":"New York","State":"NY","ICAO":"KJFK","IATA":"JFK","SupportedAirport":true,"Delay":false,"DelayCount":0,"Status":[{"Reason":"No known delays for this airport"}],"Weather":{"Weather":[{"Temp":["A Few
 Clouds"]}],"Visibility":[10.00],"Meta":[{"Credit":"NOAA's National Weather Service","Url":"http://weather.gov/","Updated":"Last Updated on Jun 8 2020, 1:51 am EDT"}],"Temp":["64.0 F (17.8 C)"],"Wind":["North at 6.9"]}}
Mon Jun  8 08:49:41 CEST 2020
{"Name":"John F Kennedy Intl","City":"New York","State":"NY","ICAO":"KJFK","IATA":"JFK","SupportedAirport":true,"Delay":false,"DelayCount":0,"Status":[{"Reason":"No known delays for this airport"}],"Weather":{"Weather":[{"Temp":["A Few Clouds"]}],"Visibility":[10.00],"Meta":[{"Credit":"NOAA's National Weather Service","Url":"http://weather.gov/","Updated":"Last Updated on Jun 8 2020, 1:51 am EDT"}],"Temp":["64.0 F (17.8 C)"],"Wind":["North at 6.9"]}}
```
For me, it looks like the component itself times out, and never starts? And I would like to debug that for you, so we can see where we have to change things. It even might be that the component is looking for something it cannot find when loaded?

Regards! Jacco

**Comment by ntilley905** [comment]
I'm working on this issue now, or at least attempting to. You are correct in your analysis that the component never loads for you, but I'm not yet sure why. The error you're getting is happening during the initial platform setup, and my first step is just going to be to handle HTTP errors (like the TimeoutError you're getting) into a different handling, rather than just exit. That won't fix the issue of why it's happening, but it should at least be able to provide for a try again after some period of time. 

Thanks for the CLI output. Just to clarify, that's from the same computer that runs your HA instance? I sometimes have tricky DNS issues on my HA Raspberry Pi, but that's probably just a me issue. I actually was having the same TimeoutError as you yesterday, I hadn't checked my own logs when you posted this but it was in there. It's back today though, so maybe try a restart and see if it goes away (for now). 

In terms of debugging, as of the current release there isn't much. You can enable debug log level, instructions below, but with where your instance is exiting, there won't be any additional information in the logs. I'll probably modify that as well when I add the additional error handling, just have to think about what would be useful.

To enable debug log level, go to the Developer Tools page on your Home Assistant instance, then go to the services tab. The service is `logger.set_level` and the service data would be `custom_component.faastatus: debug`

**Comment by Haringstad** [comment]
Hey, great that you put so much effort in! And to answer your question: Yes, I did run the curl loop on the pi that also runs HA. I will try also a restart, and the debug info you provided. Let's see where we can get this! And again: **great job, and thank you for your efforts!**

**Comment by ntilley905** [comment]
@Haringstad did the restart clear this up? Trying to rule out this being a weird one time API issue. 

Also, for some further troubleshooting, I see you’re running Home Assistant Core, so no supervisor? I sometimes have issues with the HassOS DNS that have caused problems with this component.

**Comment by Haringstad** [comment]
@ntilley905 I am running HA on a Raspi 4, with supervisor, in docker environment. I've noticed the "coredns" being a *pain* in the behind, but solved that. The restart didn't clear it up, and keep getting the message that "faastatus" isn't found by HA at all. No debug, nothing whatsoever that provides me with info, so I am a bit lost here. Even the debug does not give me any info in the logs at all.

**Comment by ntilley905** [comment]
> keep getting the message that "faastatus" isn't found by HA at all. 
> 
> 

You’re referring to the same TimeoutError that you posted in the initial post? Or is it a different error now?

**Comment by Haringstad** [comment]
Right now, with full debug, I don't even see anything anymore? Only the notifications show the message that faastatus  isn't configured.

**Comment by ntilley905** [comment]
You will probably only get the error message in the log at startup as it seems like it’s attempting to setup the component and failing. If the component fails to setup, it only tries once and there won’t be any additional information in the logs. The only attempt once part is a HA thing, not something specific to this component. 

I’m still trying to think of what could be causing this issue aside from some kind of strange network problem. The way the component currently works is that during initial setup, it calls the API once to get the name of the airport, which it uses for the sensor. If that fails, the component fails to setup. If that succeeds, it sets it up and then handles connection errors much more smoothly. I’m going to do some digging to see if there is a better way to handle a connection error during setup.

**Comment by Haringstad** [comment]
This sounds like some form of delay should be implemented, so the first API call would be done after (in my case) hassio_dns docker is properly functional? Because that hassio_dns docker has already caused some people a major migraine in the past? It's because I am swamped with work atm, that I don't had time (yet) to dive into the code. I am sorry for that. But I'll see if I can dive into it in the coming days!

**Comment by ntilley905** [comment]
@Haringstad sorry for the crazy long delay (4 months holy cow) but I've been working on a major update to this component that would also help fix your issue. It's done now, pending approval, and it'll also add it as a core component to Home Assistant instead of this custom component. Once it gets approved and merged I'll be deprecating this custom component.

**Comment by Haringstad** [comment]
Nathan, No worries at all! We have a couple of sayings here:

Better late than never, and, what is put in a good barrel, doesn't spoil!
So, in other words, it's worth the wait!

And, this also means that you've been working pretty hard, to accomplish
this! I would like to beta-test if you don't mind?

Regards,

Jacco van Koll

**Comment by ntilley905** [comment]
If you'd like to try out the new component before it gets merged, you should be able to download the files from here: https://github.com/home-assistant/core/tree/e9e814c629d6c51c89ed34a4865bce88f90d38e7/homeassistant/components/faadelays

Once you download all of those you can put them in a custom_component called `faadelays` and it should be available for UI configuration. Note that there are several changes from the last version of this custom component, the biggest ones being that it is now UI configurable (YAML is not supported at all) and there are 5 binary sensors exposed for each delay type, rather than just one sensor with lots of attributes. 

Let me know if you find any issues (or you can comment them at the core pull request [here](https://github.com/home-assistant/core/pull/41347) or if you have any trouble getting it installed as a custom component. I appreciate you giving it a test run!

**Comment by Haringstad** [comment]
Hey! PERFECT! Will do that in a little bit (20 minutes or so) and let
you know!

Regards,

Jacco van Koll

**Comment by Haringstad** [comment]
Yes! Works! Can I add multiple airports? Or should I just try?

Regards,

Jacco van Koll

**Comment by ntilley905** [comment]
Great to hear!! As far as I know you're the first person aside from me who has tried it. 

You should be able to add as many as you'd like by the same process of adding a new integration.

**Comment by Haringstad** [comment]
Don't know, if this would be how it supposed to look like?

Will add a proper image!

Regards,

Jacco van Koll

**Comment by Haringstad** [comment]
Like this one ;-)

![DeepinScreenshot_select-area_20201006200915](https://user-images.githubusercontent.com/7832166/95242821-05847d80-0810-11eb-8c48-6d2d05187164.png)

**Comment by ntilley905** [comment]
Yep, that looks right to me! The states will change to `True` if a delay is present and then the additional details are presented in the attributes.

**Comment by Haringstad** [comment]
Perfect! BTW, It would be nice, if you would add the "weather data" in a new version!!! AND **GREAT JOB!** Thank you!
This was **certainly worth the waiting**!!!!!!!

**Comment by ntilley905** [comment]
That's on the roadmap! I want to go ahead and get it merged as a new integration and then I'll look into adding that as a sensor component. I appreciate you taking a look at it!
