### ISSUE TITLE
How do I get new airports added to the available list?

### ISSUE THREAD

**Issue by daxm** [ntilley905/faastatus#9]
How do I get new airports added to the available list?

**Comment by ntilley905** [comment]
Unfortunately that list is from the FAA itself as the airports that the API supports. I have seen other airports pop up before on the other API endpoint that lists all airports with delays, but I'm not sure that those would then be supported at the endpoint that this integration uses.

**Comment by Haringstad** [comment]
You can actually try yourself, by using the url, and adding the airport code. 

For example:
https://soa.smext.faa.gov/asws/api/airport/status/SWF

Works fine.

**Comment by ntilley905** [comment]
You are right, and this is something I've wondered. On the API reference [here](url), they list that those are the only airports that return data. But if you call the API with an unsupported airport it just returns a `"SupportedAirport":false` and then works anyways. I'll probably release a point update to allow unsupported airports with an info in the logger that the airport isn't officially supported and then allow it to run anyways.

**Comment by ntilley905** [comment]
Support for unsupported airports (clear as mud, I know) has been added in v0.3.0. There are details in the release notes, but essentially the component will attempt to get data for anything passed into the ID field. If it does not get any data, it returns an error and does not setup the component. Otherwise, it sets it up and returns a warning if it is not an "officially supported" airport.
